language: scala
scala:
  - 2.12.3

services:
  - docker

before_install:
  #  If we don't run it in dettached mode then travis is blocked and cannot carry on the build
  - docker-compose up -d

script:
  - docker exec container_scala_sbt sbt test